apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-acr-cache
  annotations:
    meta.crossplane.io/maintainer: Aaron Spiegel <spiegela@gmail.com>
    meta.crossplane.io/source: github.com/Qbeast-io/provider-acr-cache
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: "Provider for managing ACR cache built using the Go template and related Pulumi providers"
